# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e5dd3e92529f2236ec5e47a79dc8370c9c5d6d8edccf3950cfd4519308476dc5b195cbff202fb7af9291a220f8d78e565035ead36940c7bb74febf736d87f13

test:
  secret_key_base: 9ab233a490393e3021f22c369db52b288ba9b8b72bd3c2d71e12b7c895f1ece313b078036ae92d0d23987a811159f06d3a8d5caca27fa2713f6fa8cbe0c8131b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
